INSERT INTO AlternativeValue (id, form, same_as) VALUES (1, 'rodzaj żeński', 22);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (2, 'rodzaj ż', 22);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (3, 'r ż', 22);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (4, 'rodzaj f', 22);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (8, 'zaimek', 1);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (9, 'mianownik', 12);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (10, 'liczba pojedyncza', 24);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (11, 'biernik', 15);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (12, 'rodzaj m3', 21);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (13, 'osoba trzecia', 28);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (14, 'aspekt niedokonany', 33);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (15, 'czas teraźniejszy', 34);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (16, 'tryb oznajmujący', 37);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (17, 'narzędnik', 16);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (18, 'liczba mnoga', 25);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (19, 'dopełniacz', 13);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (20, 'rodzaj m1', 19);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (21, 'rodzaj n', 23);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (22, 'czas przeszły', 35);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (23, 'osoba pierwsza', 26);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (24, 'aspekt dokonany', 32);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (25, 'czas przyszły', 36);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (26, 'stopień wyższy', 30);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (27, 'stopień równy', 29);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (28, 'miejscownik', 17);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (29, 'trzecia osoba', 28);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (30, 'rodzaj nijaki', 23);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (31, 'pierwsza osoba', 26);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (32, 'wołacz', 18);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (33, 'rodzaj m2', 20);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (34, 'celownik', 14);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (35, 'l. poj.', 24);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (36, 'l. mn.', 25);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (37, 'osoba druga', 27);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (38, 'mnoga', 25);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (39, 'pojedyncza', 24);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (40, 'l.pojedyncza', 24);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (41, 'l.mnoga', 25);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (42, 'm 1', 19);
INSERT INTO AlternativeValue (id, form, same_as) VALUES (43, 'prim', 26);
