INSERT INTO Category (id, name) VALUES (1, 'class');
INSERT INTO Category (id, name) VALUES (2, 'case');
INSERT INTO Category (id, name) VALUES (3, 'gend');
INSERT INTO Category (id, name) VALUES (4, 'numb');
INSERT INTO Category (id, name) VALUES (5, 'pers');
INSERT INTO Category (id, name) VALUES (6, 'degr');
INSERT INTO Category (id, name) VALUES (7, 'aspe');
INSERT INTO Category (id, name) VALUES (8, 'time');
INSERT INTO Category (id, name) VALUES (9, 'mood');
